### ISSUE TITLE
[UX tweak] Submitted an existing email triggers an error in the newsletter sign up field

### ISSUE THREAD

**Issue by ericwichman** [notairick/designclimateaction#1]
**Problem**

Entering an existing email into the newsletter sign up field and submitting it triggers a generic error message that doesn't clearly communicate what's happened to the user.

**Impact**

People visiting the site for the first time, but who've provided their email to the associated Mailchimp account may believe the newsletter sign up form is broken.

**Options**

- Interpret the error for better UX e.g. "This email has already been subscribed" or similar

**Comment by fraserpage** [comment]
I've updated the site so that the form shows the actual error mailchimp responds with. That said, I'm seeing 'Please enter a value' as the error when entering any valid email. I think there may be a mismatch between the form field names on the site and in your mailchimp account. Requested embed code to test this.

**Comment by fraserpage** [comment]
Removed the form. Linked to the mailchimp-hosted sign up form instead.
